version: '3.9'

services:
  web:
    build:       
      context: ./
      dockerfile: Dockerfile.blog
    ports:
      - "8000:80"
    depends_on:
      - api
      - postgres
    networks:
      - app-network

  api:
    build:       
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - "8001:80"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
      POSTGRES_DB: "dbTechChallenge2"
      POSTGRES_USER: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge