name: Build and Deploy to Azure Container Instance

on:
  push:
    branches:
      - master 
env:
  REGISTRY_NAME: ${{ vars.REGISTRY_NAME }}
  WEB_SERVICE: blog
  API_SERVICE: api
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test
      
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set property string value in a json file
      uses: benday-inc/set-property-value-in-appsettings@v1.4
      with:
        # Path to the json file to edit (appsettings.json)
        pathToSettingsFile: '${{ github.workspace }}/Blog/appsettings.json'
        keyname1: JwtSettings
        keyname2: Api
        valueToSet: ${{ env.API_SERVICE }}-fiap.eastus2.azurecontainer.io

    - name: Set property string value in a json file
      uses: benday-inc/set-property-value-in-appsettings@v1.4
      with:
        # Path to the json file to edit (appsettings.json)
        pathToSettingsFile: '${{ github.workspace }}/Blog/appsettings.json'
        keyname1: AzureBlobStorage
        keyname2: StorageConnectionString
        valueToSet: ${{ secrets.StorageConnectionString }}

    - name: Set property string value in a json file
      uses: benday-inc/set-property-value-in-appsettings@v1.4
      with:
        # Path to the json file to edit (appsettings.json)
        pathToSettingsFile: '${{ github.workspace }}/Api/appsettings.json'
        keyname1: ConnectionStrings
        keyname2: DefaultConnection
        valueToSet: ${{ secrets.CONNECTION_STRING }}

    - name: Set property string value in a json file
      uses: benday-inc/set-property-value-in-appsettings@v1.4
      with:
        # Path to the json file to edit (appsettings.json)
        pathToSettingsFile: '${{ github.workspace }}/Api/appsettings.json'
        keyname1: ConnectionStrings
        keyname2: BlogConnection
        valueToSet: ${{ secrets.BLOG_CONNECTION_STRING }}
        
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.REGISTRY_NAME }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and push web service
      run: |
        docker build -t ${{ env.REGISTRY_NAME }}/${{ env.WEB_SERVICE }}:${{ github.sha }} --file Dockerfile.blog .
        docker push ${{ env.REGISTRY_NAME }}/${{ env.WEB_SERVICE }}:${{ github.sha }}

    - name: Build and push api service
      run: |
        docker build -t ${{ env.REGISTRY_NAME }}/${{ env.API_SERVICE }}:${{ github.sha }} --file Dockerfile.api .
        docker push ${{ env.REGISTRY_NAME }}/${{ env.API_SERVICE }}:${{ github.sha }}

                    

